version: '3'
services:
  web:
    image: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    environment:
      STAGE: local
      DOMAINS: 'example.local -> http://web:8000'
